### Your name:

Rachit Bhatia

### Collaborators:

<pre> Enter the name of the people you worked with if any</pre>

In [3]:
import numpy as np
import pandas as pd

# to make this notebook's output stable across runs
np.random.seed(123)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

### Classification

Q1. Build a classification model for the default of credit card clients dataset. More info here:
https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

- Explore the data
- Make sure you build a full data pipeline
- Do you require any data pre-processing? Are all the features useful? (Use only raw features)
- set the random seed to 123 (For splitting or any other random algorithm)
- Split data into training (80%) and testing (20%)
- Follow similar procedure as the one for week 2 (End-to-end Machine Learning Project). Remember apendix B
- Study the ROC Curve, decide threshold
- Use 2 classifiers.
    - Random Forest
        - tune only: n_estimators: {4, 5, 10, 20, 50} 
    - KNN Classfier 
        - tune only: n_neighbors: {3, 5, 10, 20} 
    - Which one performs better in the cross validation?
    
http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

- Cross-validation with 5-folds

- Other paramenters -> Use default

In [13]:
### Your code here

## Feel free to use multiple cells

df = pd.read_excel("./datasets/credit_cards/default of credit card clients.xls", 
                   sheet = 0, skiprows= 1, header = 0)

In [14]:
target = df['default payment next month'].copy()

df = df.drop('ID', axis=1)
#df_num.drop('SEX', axis=1)
df = df.drop('default payment next month', axis=1)

In [15]:
df

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000,2,2,1,24,2,2,-1,-1,-2,...,689,0,0,0,0,689,0,0,0,0
1,120000,2,2,2,26,-1,2,0,0,0,...,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,90000,2,2,2,34,0,0,0,0,0,...,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000
3,50000,2,2,1,37,0,0,0,0,0,...,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000
4,50000,1,2,1,57,-1,0,-1,0,0,...,35835,20940,19146,19131,2000,36681,10000,9000,689,679
5,50000,1,1,2,37,0,0,0,0,0,...,57608,19394,19619,20024,2500,1815,657,1000,1000,800
6,500000,1,1,2,29,0,0,0,0,0,...,445007,542653,483003,473944,55000,40000,38000,20239,13750,13770
7,100000,2,2,2,23,0,-1,-1,0,0,...,601,221,-159,567,380,601,0,581,1687,1542
8,140000,2,3,1,28,0,0,2,0,0,...,12108,12211,11793,3719,3329,0,432,1000,1000,1000
9,20000,1,3,2,35,-2,-2,-2,-2,-1,...,0,0,13007,13912,0,0,0,13007,1122,0
10,200000,2,3,2,34,0,0,2,0,0,...,5535,2513,1828,3731,2306,12,50,300,3738,66
11,260000,2,1,2,51,-1,-1,-1,-1,-1,...,9966,8517,22287,13668,21818,9966,8583,22301,0,3640
12,630000,2,2,2,41,-1,0,-1,-1,-1,...,6500,6500,6500,2870,1000,6500,6500,6500,2870,0
13,70000,1,2,2,30,1,2,2,0,0,...,65701,66782,36137,36894,3200,0,3000,3000,1500,0
14,250000,1,1,2,29,0,0,0,0,0,...,63561,59696,56875,55512,3000,3000,3000,3000,3000,3000
15,50000,2,3,3,23,1,2,0,0,0,...,28116,28771,29531,30211,0,1500,1100,1200,1300,1100
16,20000,1,1,2,24,0,0,2,2,2,...,17428,18338,17905,19104,3200,0,1500,0,1650,0
17,320000,1,1,1,49,0,0,0,-1,-1,...,194663,70074,5856,195599,10358,10000,75940,20000,195599,50000
18,360000,2,1,1,49,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
19,180000,2,1,2,29,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
20,130000,2,3,2,39,0,0,0,0,0,...,24489,20616,11802,930,3000,1537,1000,2000,930,33764
21,120000,2,2,1,39,-1,-1,-1,-1,-1,...,316,0,632,316,316,316,0,632,316,0
22,70000,2,2,2,26,2,0,0,2,2,...,45020,44006,46905,46012,2007,3582,0,3601,0,1820
23,450000,2,1,1,40,-2,-2,-2,-2,-2,...,1473,560,0,0,19428,1473,560,0,0,1128
24,90000,1,1,2,23,0,0,0,-1,0,...,0,5398,6360,8292,5757,0,5398,1200,2045,2000
25,50000,1,3,2,23,0,0,0,0,0,...,36023,28967,29829,30046,1973,1426,1001,1432,1062,997
26,60000,1,1,2,27,1,-2,-1,-1,-1,...,259,-57,127,-189,0,1000,0,500,0,1000
27,50000,2,3,2,30,0,0,0,0,0,...,17163,17878,18931,19617,1300,1300,1000,1500,1000,1012
28,50000,2,3,1,47,-1,-1,-1,-1,-1,...,3416,2040,30430,257,3415,3421,2044,30430,257,0
29,50000,1,1,2,26,0,0,0,0,0,...,17496,17907,18375,11400,1500,1500,1000,1000,1600,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29970,360000,1,1,1,34,-1,-1,-1,0,0,...,64069,49005,8676,19487,52951,64535,8907,53,19584,16080
29971,80000,1,3,1,36,0,0,0,0,0,...,68279,69674,71070,73612,2395,2500,2530,2556,3700,3000
29972,190000,1,1,1,37,0,0,0,0,0,...,5869,29223,19616,148482,2000,3869,25128,10115,148482,4800
29973,230000,1,2,1,35,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
29974,50000,1,2,1,37,1,2,2,2,0,...,4328,2846,1585,1324,0,3000,0,0,1000,1000
29975,220000,1,2,1,41,0,0,-1,-1,-2,...,1369,5924,1759,1824,8840,6643,5924,1759,1824,7022
29976,40000,1,2,2,47,2,2,3,2,2,...,53415,51259,47151,46934,4000,0,2000,0,3520,0
29977,420000,1,1,2,34,0,0,0,0,0,...,140011,141695,144839,147954,7000,7000,5500,5500,5600,5000
29978,310000,1,2,1,39,0,0,0,0,0,...,233854,219409,216540,210675,10029,9218,10029,8049,8040,10059
29979,180000,1,1,1,32,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
29980,50000,1,3,2,42,0,0,0,0,0,...,49397,50360,19971,19694,10000,4000,5000,3000,4500,2000
29981,50000,1,2,1,44,1,2,2,2,0,...,33101,28192,22676,14647,2300,1700,0,517,503,585
29982,90000,1,2,1,36,0,0,0,0,0,...,10306,11328,12036,14329,1500,1500,1500,1200,2500,0
29983,20000,1,2,1,44,-2,-2,-2,-2,-2,...,2712,2882,9235,1719,2890,2720,2890,9263,1824,1701
29984,30000,1,2,2,38,-1,-1,-2,-1,-1,...,2939,1993,1907,3319,923,2977,1999,3057,3319,1000
29985,240000,1,1,2,30,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
29986,360000,1,1,2,35,-1,-1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
29987,130000,1,1,2,34,0,0,0,0,0,...,15546,108047,93708,97353,3000,2000,93000,4000,5027,4005
29988,250000,1,1,1,34,0,0,0,0,0,...,243075,245750,175005,179687,65000,8800,9011,6000,7000,6009
29989,150000,1,1,2,35,-1,-1,-1,-1,-1,...,-3,780,0,0,9054,0,783,0,0,0
29990,140000,1,2,1,41,0,0,0,0,0,...,139110,138262,49675,46121,6000,7000,4228,1505,2000,2000
29991,210000,1,2,1,34,3,2,2,2,2,...,2500,2500,2500,2500,0,0,0,0,0,0
29992,10000,1,3,1,43,0,0,0,-2,-2,...,0,0,0,0,2000,0,0,0,0,0
29993,100000,1,1,2,38,0,-1,-1,0,0,...,102996,70626,69473,55004,2000,111784,4000,3000,2000,2000
29994,80000,1,2,2,34,2,2,2,2,2,...,79384,77519,82607,81158,7000,3500,0,7000,0,4000
29995,220000,1,3,1,39,0,0,0,0,0,...,208365,88004,31237,15980,8500,20000,5003,3047,5000,1000
29996,150000,1,3,2,43,-1,-1,-1,-1,0,...,3502,8979,5190,0,1837,3526,8998,129,0,0
29997,30000,1,2,2,37,4,3,2,-1,0,...,2758,20878,20582,19357,0,0,22000,4200,2000,3100
29998,80000,1,3,1,41,1,-1,0,0,0,...,76304,52774,11855,48944,85900,3409,1178,1926,52964,1804
29999,50000,1,2,1,46,0,0,0,0,0,...,49764,36535,32428,15313,2078,1800,1430,1000,1000,1000

Split the date into 80/20

In [17]:
#msk = np.random.rand(len(df)) < 0.8
#train = df[msk]
#test = df[~msk]
from sklearn.model_selection import train_test_split
train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.80, random_state=42)

In [20]:
train

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
28388,390000,2,1,1,42,0,0,0,0,0,...,90383,55212,29701,-1429,10021,4000,15046,20000,0,10090
24763,110000,1,5,1,36,-1,0,0,0,0,...,50526,51816,34262,23366,28000,20000,3000,3000,3000,3000
25957,260000,2,1,1,29,0,0,0,-2,-2,...,0,0,0,0,3090,0,0,0,0,141516
20588,110000,1,1,2,29,0,0,0,0,0,...,142622,73702,75513,77111,7316,3000,6000,3000,2935,3011
5850,200000,1,1,2,28,0,-1,2,2,-1,...,10373,2669,1024,170722,22182,7,0,6177,180722,5000
6129,20000,1,1,2,33,2,0,0,-2,-2,...,0,0,0,0,5000,0,0,0,0,0
5447,240000,2,1,1,29,0,0,-1,0,0,...,194043,194991,192800,178318,1000,194043,6530,7000,7000,10000
3129,180000,1,1,2,29,0,0,0,0,2,...,98354,105327,107500,105614,3500,4000,8600,4000,0,8100
16279,130000,2,2,2,33,0,0,0,0,0,...,104394,103798,82816,78727,3775,3988,6000,3784,3010,3200
15632,90000,2,2,2,25,1,-1,-1,-1,-1,...,420,0,1140,150,840,420,0,1140,0,570
18380,70000,2,2,2,22,2,0,0,0,0,...,19998,22919,23128,23030,1313,1689,4000,958,1036,6000
910,90000,2,1,2,25,2,2,2,2,0,...,92860,88533,90942,88813,8300,2400,1000,4000,3600,4000
3968,50000,2,1,2,26,1,-1,-1,0,0,...,2576,12576,22397,15944,1950,2576,10000,10000,685,612
27852,50000,2,1,2,27,2,0,0,0,2,...,49140,49423,48377,48158,3000,2525,3900,0,2000,4500
26708,50000,1,1,2,25,-1,0,0,0,0,...,10745,9994,16829,13051,3000,9537,5000,10000,5000,2000
10165,140000,1,2,1,40,0,0,0,0,0,...,82083,83029,84737,94101,4000,3900,3200,3200,10800,0
336,260000,2,1,2,30,0,0,0,0,0,...,159988,158114,158762,159108,10000,8000,6000,7000,7000,6000
26709,360000,1,3,1,27,-2,-2,-2,-2,-2,...,2999,-1,-1,-1,780,3021,0,0,0,0
29944,80000,1,2,2,39,3,2,0,0,0,...,74968,23867,23130,0,0,2968,1867,463,0,0
24986,20000,1,3,1,38,0,0,-1,0,0,...,19648,18459,18824,19220,1400,19648,1307,672,698,718
2985,120000,1,2,2,27,0,0,0,0,0,...,26523,20554,19348,17439,1789,2037,659,802,640,513
10878,30000,1,2,2,25,1,2,3,2,0,...,27332,26597,27512,57002,3000,0,0,1500,1600,900
15916,20000,2,2,1,30,0,0,0,-1,-1,...,10419,780,0,0,1225,1015,780,0,0,0
21004,80000,1,2,2,32,2,0,0,0,0,...,67253,67352,74448,72928,3000,4005,2500,10000,0,5000
22915,210000,2,2,1,34,0,0,0,0,0,...,212391,208931,146005,145343,9500,9207,8500,5200,5200,5000
11669,210000,1,1,2,32,0,0,0,0,0,...,17383,172065,181981,174744,5000,1400,155000,12700,0,6300
20862,240000,1,2,1,45,0,0,0,0,0,...,223853,225623,221130,225446,10000,9000,10000,8301,9000,13000
19942,360000,2,2,1,45,0,0,-2,-2,-1,...,0,0,150,1728,0,0,0,150,1728,0
13907,20000,1,2,1,36,0,0,0,0,0,...,21017,19772,15628,12501,1739,1453,691,512,1430,0
11001,40000,2,1,2,23,-1,-1,2,0,0,...,34113,35513,36513,35956,4082,0,2000,1000,500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20939,50000,1,3,1,37,0,0,0,0,0,...,45559,46164,46685,47272,2021,3259,1754,1665,1723,2099
17568,80000,2,1,1,37,-1,-1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
6420,200000,1,2,2,33,0,0,0,0,0,...,83290,85085,89707,63787,2972,2952,3107,6056,0,3000
5051,20000,2,1,2,23,0,0,0,-2,-2,...,-340,-780,-780,780,1031,650,0,0,1560,150
5311,80000,1,2,1,46,0,0,2,0,0,...,26128,29137,30283,30523,10036,15,5003,3003,2007,1007
2433,100000,2,1,2,36,1,-1,-1,-2,-2,...,0,0,0,0,780,0,0,7600,0,0
23333,150000,2,1,2,36,0,0,0,0,0,...,49096,49848,52007,54161,5000,5000,3000,3000,3000,3500
26967,350000,1,1,2,32,0,0,0,0,0,...,16991,18541,20075,20491,2000,3000,2000,2001,580,677
769,200000,2,1,1,35,-2,-2,-2,-2,-2,...,1265,2473,0,0,4266,1667,2473,0,0,0
1685,230000,2,1,1,61,-2,-2,-2,-2,-2,...,1443,1443,1443,1443,1443,1443,1443,1443,1443,1443
8322,210000,2,2,2,28,0,0,-1,0,0,...,259323,139861,1684,826,61,130000,10000,1684,826,1793
16023,330000,2,1,1,36,1,-2,-2,-1,-1,...,0,469,150,3661,0,0,469,150,3661,3800
27495,170000,1,2,1,57,-1,-1,-1,-1,0,...,396,792,396,396,0,3396,792,0,396,396
11363,310000,2,2,1,35,0,0,-1,0,0,...,11505,17264,10919,3185,1041,11512,7271,5000,3215,15558
28020,80000,2,2,1,29,2,0,0,0,0,...,81130,49407,49067,50234,3500,3700,1800,1900,3000,2000
14423,50000,2,3,1,24,-1,-1,2,0,-1,...,20731,13555,2338,41191,3000,15,587,2338,41191,18957
21962,150000,2,1,2,27,-2,-2,-2,-1,0,...,32662,59350,41136,28596,3449,46128,60260,30218,17000,20133
4426,110000,2,2,1,28,0,0,0,0,0,...,44625,45579,46843,48062,2027,2500,2000,2000,2000,1600
29910,310000,1,2,2,30,-2,-2,-2,-2,-2,...,780,0,0,291,0,1003,0,0,291,173
16850,230000,1,2,3,37,-1,0,0,0,0,...,20474,26492,326,1056,10000,5000,16492,0,1056,326
6265,90000,2,2,1,38,0,0,0,0,0,...,89876,49922,46302,45430,3900,3487,1629,4000,3000,813
22118,80000,2,2,3,29,-1,-1,2,-1,-1,...,6187,7757,8451,6625,14349,5,7761,8460,6630,6218
11284,280000,2,1,1,32,1,-2,-1,0,0,...,3508,3508,-200,-200,0,3508,0,0,0,0
11964,160000,2,2,1,42,0,0,0,0,0,...,170142,119529,122059,111378,8450,5289,4022,4195,3986,3958
21575,60000,2,1,2,24,0,0,0,0,0,...,34783,32158,28991,28434,1553,2000,1508,1080,1003,1000
29802,50000,1,2,2,32,0,0,0,0,0,...,55739,55957,29238,6119,2000,3000,1591,72,1134,73421
5390,200000,1,1,2,37,2,2,2,2,2,...,168386,164182,169029,172084,13500,6000,0,7500,6000,4000
860,50000,1,1,2,26,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
15795,70000,2,2,2,25,0,0,0,0,2,...,51152,35122,28633,28039,3000,2000,4500,1200,0,1200
23654,160000,2,2,1,36,-2,-2,-2,-2,-2,...,3640,2935,1603,14129,0,3660,3135,1650,14200,1500

remove cat variable to new one

In [21]:
df_cat = train[['SEX','EDUCATION','MARRIAGE']].copy()

In [22]:
df_cat

       SEX  EDUCATION  MARRIAGE
28388    2          1         1
24763    1          5         1
25957    2          1         1
20588    1          1         2
5850     1          1         2
6129     1          1         2
5447     2          1         1
3129     1          1         2
16279    2          2         2
15632    2          2         2
18380    2          2         2
910      2          1         2
3968     2          1         2
27852    2          1         2
26708    1          1         2
10165    1          2         1
336      2          1         2
26709    1          3         1
29944    1          2         2
24986    1          3         1
2985     1          2         2
10878    1          2         2
15916    2          2         1
21004    1          2         2
22915    2          2         1
11669    1          1         2
20862    1          2         1
19942    2          2         1
13907    1          2         1
11001    2          1         2
...    ...        ...       ...
20939    1          3         1
17568    2          1         1
6420     1          2         2
5051     2          1         2
5311     1          2         1
2433     2          1         2
23333    2          1         2
26967    1          1         2
769      2          1         1
1685     2          1         1
8322     2          2         2
16023    2          1         1
27495    1          2         1
11363    2          2         1
28020    2          2         1
14423    2          3         1
21962    2          1         2
4426     2          2         1
29910    1          2         2
16850    1          2         3
6265     2          2         1
22118    2          2         3
11284    2          1         1
11964    2          2         1
21575    2          1         2
29802    1          2         2
5390     1          1         2
860      1          1         2
15795    2          2         2
23654    2          2         1

[6000 rows x 3 columns]

In [23]:
df_num = train
df_num

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
28388,390000,2,1,1,42,0,0,0,0,0,...,90383,55212,29701,-1429,10021,4000,15046,20000,0,10090
24763,110000,1,5,1,36,-1,0,0,0,0,...,50526,51816,34262,23366,28000,20000,3000,3000,3000,3000
25957,260000,2,1,1,29,0,0,0,-2,-2,...,0,0,0,0,3090,0,0,0,0,141516
20588,110000,1,1,2,29,0,0,0,0,0,...,142622,73702,75513,77111,7316,3000,6000,3000,2935,3011
5850,200000,1,1,2,28,0,-1,2,2,-1,...,10373,2669,1024,170722,22182,7,0,6177,180722,5000
6129,20000,1,1,2,33,2,0,0,-2,-2,...,0,0,0,0,5000,0,0,0,0,0
5447,240000,2,1,1,29,0,0,-1,0,0,...,194043,194991,192800,178318,1000,194043,6530,7000,7000,10000
3129,180000,1,1,2,29,0,0,0,0,2,...,98354,105327,107500,105614,3500,4000,8600,4000,0,8100
16279,130000,2,2,2,33,0,0,0,0,0,...,104394,103798,82816,78727,3775,3988,6000,3784,3010,3200
15632,90000,2,2,2,25,1,-1,-1,-1,-1,...,420,0,1140,150,840,420,0,1140,0,570
18380,70000,2,2,2,22,2,0,0,0,0,...,19998,22919,23128,23030,1313,1689,4000,958,1036,6000
910,90000,2,1,2,25,2,2,2,2,0,...,92860,88533,90942,88813,8300,2400,1000,4000,3600,4000
3968,50000,2,1,2,26,1,-1,-1,0,0,...,2576,12576,22397,15944,1950,2576,10000,10000,685,612
27852,50000,2,1,2,27,2,0,0,0,2,...,49140,49423,48377,48158,3000,2525,3900,0,2000,4500
26708,50000,1,1,2,25,-1,0,0,0,0,...,10745,9994,16829,13051,3000,9537,5000,10000,5000,2000
10165,140000,1,2,1,40,0,0,0,0,0,...,82083,83029,84737,94101,4000,3900,3200,3200,10800,0
336,260000,2,1,2,30,0,0,0,0,0,...,159988,158114,158762,159108,10000,8000,6000,7000,7000,6000
26709,360000,1,3,1,27,-2,-2,-2,-2,-2,...,2999,-1,-1,-1,780,3021,0,0,0,0
29944,80000,1,2,2,39,3,2,0,0,0,...,74968,23867,23130,0,0,2968,1867,463,0,0
24986,20000,1,3,1,38,0,0,-1,0,0,...,19648,18459,18824,19220,1400,19648,1307,672,698,718
2985,120000,1,2,2,27,0,0,0,0,0,...,26523,20554,19348,17439,1789,2037,659,802,640,513
10878,30000,1,2,2,25,1,2,3,2,0,...,27332,26597,27512,57002,3000,0,0,1500,1600,900
15916,20000,2,2,1,30,0,0,0,-1,-1,...,10419,780,0,0,1225,1015,780,0,0,0
21004,80000,1,2,2,32,2,0,0,0,0,...,67253,67352,74448,72928,3000,4005,2500,10000,0,5000
22915,210000,2,2,1,34,0,0,0,0,0,...,212391,208931,146005,145343,9500,9207,8500,5200,5200,5000
11669,210000,1,1,2,32,0,0,0,0,0,...,17383,172065,181981,174744,5000,1400,155000,12700,0,6300
20862,240000,1,2,1,45,0,0,0,0,0,...,223853,225623,221130,225446,10000,9000,10000,8301,9000,13000
19942,360000,2,2,1,45,0,0,-2,-2,-1,...,0,0,150,1728,0,0,0,150,1728,0
13907,20000,1,2,1,36,0,0,0,0,0,...,21017,19772,15628,12501,1739,1453,691,512,1430,0
11001,40000,2,1,2,23,-1,-1,2,0,0,...,34113,35513,36513,35956,4082,0,2000,1000,500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20939,50000,1,3,1,37,0,0,0,0,0,...,45559,46164,46685,47272,2021,3259,1754,1665,1723,2099
17568,80000,2,1,1,37,-1,-1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
6420,200000,1,2,2,33,0,0,0,0,0,...,83290,85085,89707,63787,2972,2952,3107,6056,0,3000
5051,20000,2,1,2,23,0,0,0,-2,-2,...,-340,-780,-780,780,1031,650,0,0,1560,150
5311,80000,1,2,1,46,0,0,2,0,0,...,26128,29137,30283,30523,10036,15,5003,3003,2007,1007
2433,100000,2,1,2,36,1,-1,-1,-2,-2,...,0,0,0,0,780,0,0,7600,0,0
23333,150000,2,1,2,36,0,0,0,0,0,...,49096,49848,52007,54161,5000,5000,3000,3000,3000,3500
26967,350000,1,1,2,32,0,0,0,0,0,...,16991,18541,20075,20491,2000,3000,2000,2001,580,677
769,200000,2,1,1,35,-2,-2,-2,-2,-2,...,1265,2473,0,0,4266,1667,2473,0,0,0
1685,230000,2,1,1,61,-2,-2,-2,-2,-2,...,1443,1443,1443,1443,1443,1443,1443,1443,1443,1443
8322,210000,2,2,2,28,0,0,-1,0,0,...,259323,139861,1684,826,61,130000,10000,1684,826,1793
16023,330000,2,1,1,36,1,-2,-2,-1,-1,...,0,469,150,3661,0,0,469,150,3661,3800
27495,170000,1,2,1,57,-1,-1,-1,-1,0,...,396,792,396,396,0,3396,792,0,396,396
11363,310000,2,2,1,35,0,0,-1,0,0,...,11505,17264,10919,3185,1041,11512,7271,5000,3215,15558
28020,80000,2,2,1,29,2,0,0,0,0,...,81130,49407,49067,50234,3500,3700,1800,1900,3000,2000
14423,50000,2,3,1,24,-1,-1,2,0,-1,...,20731,13555,2338,41191,3000,15,587,2338,41191,18957
21962,150000,2,1,2,27,-2,-2,-2,-1,0,...,32662,59350,41136,28596,3449,46128,60260,30218,17000,20133
4426,110000,2,2,1,28,0,0,0,0,0,...,44625,45579,46843,48062,2027,2500,2000,2000,2000,1600
29910,310000,1,2,2,30,-2,-2,-2,-2,-2,...,780,0,0,291,0,1003,0,0,291,173
16850,230000,1,2,3,37,-1,0,0,0,0,...,20474,26492,326,1056,10000,5000,16492,0,1056,326
6265,90000,2,2,1,38,0,0,0,0,0,...,89876,49922,46302,45430,3900,3487,1629,4000,3000,813
22118,80000,2,2,3,29,-1,-1,2,-1,-1,...,6187,7757,8451,6625,14349,5,7761,8460,6630,6218
11284,280000,2,1,1,32,1,-2,-1,0,0,...,3508,3508,-200,-200,0,3508,0,0,0,0
11964,160000,2,2,1,42,0,0,0,0,0,...,170142,119529,122059,111378,8450,5289,4022,4195,3986,3958
21575,60000,2,1,2,24,0,0,0,0,0,...,34783,32158,28991,28434,1553,2000,1508,1080,1003,1000
29802,50000,1,2,2,32,0,0,0,0,0,...,55739,55957,29238,6119,2000,3000,1591,72,1134,73421
5390,200000,1,1,2,37,2,2,2,2,2,...,168386,164182,169029,172084,13500,6000,0,7500,6000,4000
860,50000,1,1,2,26,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
15795,70000,2,2,2,25,0,0,0,0,2,...,51152,35122,28633,28039,3000,2000,4500,1200,0,1200
23654,160000,2,2,1,36,-2,-2,-2,-2,-2,...,3640,2935,1603,14129,0,3660,3135,1650,14200,1500

In [24]:
df_num = df_num.drop('SEX', axis=1)
df_num = df_num.drop('EDUCATION', axis=1)
df_num = df_num.drop('MARRIAGE', axis=1)

In [25]:
df_num

,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
28388,390000,42,0,0,0,0,0,0,310075,184647,90383,55212,29701,-1429,10021,4000,15046,20000,0,10090
24763,110000,36,-1,0,0,0,0,0,3385,31169,50526,51816,34262,23366,28000,20000,3000,3000,3000,3000
25957,260000,29,0,0,0,-2,-2,-2,71864,54050,0,0,0,0,3090,0,0,0,0,141516
20588,110000,29,0,0,0,0,0,0,104216,104343,142622,73702,75513,77111,7316,3000,6000,3000,2935,3011
5850,200000,28,0,-1,2,2,-1,-1,7464,22182,10373,2669,1024,170722,22182,7,0,6177,180722,5000
6129,20000,33,2,0,0,-2,-2,-2,16339,20650,0,0,0,0,5000,0,0,0,0,0
5447,240000,29,0,0,-1,0,0,0,21409,17833,194043,194991,192800,178318,1000,194043,6530,7000,7000,10000
3129,180000,29,0,0,0,0,2,2,93962,95955,98354,105327,107500,105614,3500,4000,8600,4000,0,8100
16279,130000,33,0,0,0,0,0,0,108984,106533,104394,103798,82816,78727,3775,3988,6000,3784,3010,3200
15632,90000,25,1,-1,-1,-1,-1,2,0,840,420,0,1140,150,840,420,0,1140,0,570
18380,70000,22,2,0,0,0,0,0,34970,19188,19998,22919,23128,23030,1313,1689,4000,958,1036,6000
910,90000,25,2,2,2,2,0,0,86014,92898,92860,88533,90942,88813,8300,2400,1000,4000,3600,4000
3968,50000,26,1,-1,-1,0,0,0,0,1950,2576,12576,22397,15944,1950,2576,10000,10000,685,612
27852,50000,27,2,0,0,0,2,0,48064,47691,49140,49423,48377,48158,3000,2525,3900,0,2000,4500
26708,50000,25,-1,0,0,0,0,0,45626,16533,10745,9994,16829,13051,3000,9537,5000,10000,5000,2000
10165,140000,40,0,0,0,0,0,0,77356,80113,82083,83029,84737,94101,4000,3900,3200,3200,10800,0
336,260000,30,0,0,0,0,0,0,156882,160246,159988,158114,158762,159108,10000,8000,6000,7000,7000,6000
26709,360000,27,-2,-2,-2,-2,-2,-2,1097,778,2999,-1,-1,-1,780,3021,0,0,0,0
29944,80000,39,3,2,0,0,0,0,75635,73830,74968,23867,23130,0,0,2968,1867,463,0,0
24986,20000,38,0,0,-1,0,0,0,17860,11627,19648,18459,18824,19220,1400,19648,1307,672,698,718
2985,120000,27,0,0,0,0,0,0,33474,29029,26523,20554,19348,17439,1789,2037,659,802,640,513
10878,30000,25,1,2,3,2,0,0,25787,28067,27332,26597,27512,57002,3000,0,0,1500,1600,900
15916,20000,30,0,0,0,-1,-1,-2,18354,16419,10419,780,0,0,1225,1015,780,0,0,0
21004,80000,32,2,0,0,0,0,2,79237,65301,67253,67352,74448,72928,3000,4005,2500,10000,0,5000
22915,210000,34,0,0,0,0,0,0,205475,206616,212391,208931,146005,145343,9500,9207,8500,5200,5200,5000
11669,210000,32,0,0,0,0,0,2,124838,102995,17383,172065,181981,174744,5000,1400,155000,12700,0,6300
20862,240000,45,0,0,0,0,0,0,228278,232449,223853,225623,221130,225446,10000,9000,10000,8301,9000,13000
19942,360000,45,0,0,-2,-2,-1,-1,12040,0,0,0,150,1728,0,0,0,150,1728,0
13907,20000,36,0,0,0,0,0,0,20710,21790,21017,19772,15628,12501,1739,1453,691,512,1430,0
11001,40000,23,-1,-1,2,0,0,0,32346,35595,34113,35513,36513,35956,4082,0,2000,1000,500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20939,50000,37,0,0,0,0,0,0,44320,45211,45559,46164,46685,47272,2021,3259,1754,1665,1723,2099
17568,80000,37,-1,-1,-2,-2,-2,-2,1330,0,0,0,0,0,0,0,0,0,0,0
6420,200000,33,0,0,0,0,0,2,80012,81703,83290,85085,89707,63787,2972,2952,3107,6056,0,3000
5051,20000,23,0,0,0,-2,-2,-1,11967,5252,-340,-780,-780,780,1031,650,0,0,1560,150
5311,80000,46,0,0,2,0,0,0,30773,38879,26128,29137,30283,30523,10036,15,5003,3003,2007,1007
2433,100000,36,1,-1,-1,-2,-2,-2,0,780,0,0,0,0,780,0,0,7600,0,0
23333,150000,36,0,0,0,0,0,0,43544,47751,49096,49848,52007,54161,5000,5000,3000,3000,3000,3500
26967,350000,32,0,0,0,0,0,0,43356,14236,16991,18541,20075,20491,2000,3000,2000,2001,580,677
769,200000,35,-2,-2,-2,-2,-2,-2,2257,4261,1265,2473,0,0,4266,1667,2473,0,0,0
1685,230000,61,-2,-2,-2,-2,-2,-2,1443,1443,1443,1443,1443,1443,1443,1443,1443,1443,1443,1443
8322,210000,28,0,0,-1,0,0,-2,2162,61,259323,139861,1684,826,61,130000,10000,1684,826,1793
16023,330000,36,1,-2,-2,-1,-1,-1,0,0,0,469,150,3661,0,0,469,150,3661,3800
27495,170000,57,-1,-1,-1,-1,0,-1,792,-2604,396,792,396,396,0,3396,792,0,396,396
11363,310000,35,0,0,-1,0,0,-1,14332,8257,11505,17264,10919,3185,1041,11512,7271,5000,3215,15558
28020,80000,29,2,0,0,0,0,0,80100,79368,81130,49407,49067,50234,3500,3700,1800,1900,3000,2000
14423,50000,24,-1,-1,2,0,-1,-1,18965,21647,20731,13555,2338,41191,3000,15,587,2338,41191,18957
21962,150000,27,-2,-2,-2,-1,0,0,-3706,-6108,32662,59350,41136,28596,3449,46128,60260,30218,17000,20133
4426,110000,28,0,0,0,0,0,0,41799,43152,44625,45579,46843,48062,2027,2500,2000,2000,2000,1600
29910,310000,30,-2,-2,-2,-2,-2,-2,167,-223,780,0,0,291,0,1003,0,0,291,173
16850,230000,37,-1,0,0,0,0,-1,11770,16479,20474,26492,326,1056,10000,5000,16492,0,1056,326
6265,90000,38,0,0,0,0,0,0,88758,89680,89876,49922,46302,45430,3900,3487,1629,4000,3000,813
22118,80000,29,-1,-1,2,-1,-1,-1,6441,14342,6187,7757,8451,6625,14349,5,7761,8460,6630,6218
11284,280000,32,1,-2,-1,0,0,-2,0,0,3508,3508,-200,-200,0,3508,0,0,0,0
11964,160000,42,0,0,0,0,0,0,165686,169969,170142,119529,122059,111378,8450,5289,4022,4195,3986,3958
21575,60000,24,0,0,0,0,0,0,35138,35776,34783,32158,28991,28434,1553,2000,1508,1080,1003,1000
29802,50000,32,0,0,0,0,0,0,52475,53600,55739,55957,29238,6119,2000,3000,1591,72,1134,73421
5390,200000,37,2,2,2,2,2,2,157131,166590,168386,164182,169029,172084,13500,6000,0,7500,6000,4000
860,50000,26,-2,-2,-2,-2,-2,-2,0,0,0,0,0,0,0,0,0,0,0,0
15795,70000,25,0,0,0,0,2,2,73939,70488,51152,35122,28633,28039,3000,2000,4500,1200,0,1200
23654,160000,36,-2,-2,-2,-2,-2,-2,-20,-20,3640,2935,1603,14129,0,3660,3135,1650,14200,1500

Run full pipeline

In [26]:
# Definition of the CategoricalEncoder class, copied from PR #9151.
# Just run this cell, or copy it to your code, do not try to understand it (yet).

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils import check_array
from sklearn.preprocessing import LabelEncoder
from scipy import sparse

class CategoricalEncoder(BaseEstimator, TransformerMixin):
    """Encode categorical features as a numeric array.
    The input to this transformer should be a matrix of integers or strings,
    denoting the values taken on by categorical (discrete) features.
    The features can be encoded using a one-hot aka one-of-K scheme
    (``encoding='onehot'``, the default) or converted to ordinal integers
    (``encoding='ordinal'``).
    This encoding is needed for feeding categorical data to many scikit-learn
    estimators, notably linear models and SVMs with the standard kernels.
    Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
    Parameters
    ----------
    encoding : str, 'onehot', 'onehot-dense' or 'ordinal'
        The type of encoding to use (default is 'onehot'):
        - 'onehot': encode the features using a one-hot aka one-of-K scheme
          (or also called 'dummy' encoding). This creates a binary column for
          each category and returns a sparse matrix.
        - 'onehot-dense': the same as 'onehot' but returns a dense array
          instead of a sparse matrix.
        - 'ordinal': encode the features as ordinal integers. This results in
          a single column of integers (0 to n_categories - 1) per feature.
    categories : 'auto' or a list of lists/arrays of values.
        Categories (unique values) per feature:
        - 'auto' : Determine categories automatically from the training data.
        - list : ``categories[i]`` holds the categories expected in the ith
          column. The passed categories are sorted before encoding the data
          (used categories can be found in the ``categories_`` attribute).
    dtype : number type, default np.float64
        Desired dtype of output.
    handle_unknown : 'error' (default) or 'ignore'
        Whether to raise an error or ignore if a unknown categorical feature is
        present during transform (default is to raise). When this is parameter
        is set to 'ignore' and an unknown category is encountered during
        transform, the resulting one-hot encoded columns for this feature
        will be all zeros.
        Ignoring unknown categories is not supported for
        ``encoding='ordinal'``.
    Attributes
    ----------
    categories_ : list of arrays
        The categories of each feature determined during fitting. When
        categories were specified manually, this holds the sorted categories
        (in order corresponding with output of `transform`).
    Examples
    --------
    Given a dataset with three features and two samples, we let the encoder
    find the maximum value per feature and transform the data to a binary
    one-hot encoding.
    >>> from sklearn.preprocessing import CategoricalEncoder
    >>> enc = CategoricalEncoder(handle_unknown='ignore')
    >>> enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])
    ... # doctest: +ELLIPSIS
    CategoricalEncoder(categories='auto', dtype=<... 'numpy.float64'>,
              encoding='onehot', handle_unknown='ignore')
    >>> enc.transform([[0, 1, 1], [1, 0, 4]]).toarray()
    array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
           [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])
    See also
    --------
    sklearn.preprocessing.OneHotEncoder : performs a one-hot encoding of
      integer ordinal features. The ``OneHotEncoder assumes`` that input
      features take on values in the range ``[0, max(feature)]`` instead of
      using the unique values.
    sklearn.feature_extraction.DictVectorizer : performs a one-hot encoding of
      dictionary items (also handles string-valued features).
    sklearn.feature_extraction.FeatureHasher : performs an approximate one-hot
      encoding of dictionary items or strings.
    """

    def __init__(self, encoding='onehot', categories='auto', dtype=np.float64,
                 handle_unknown='error'):
        self.encoding = encoding
        self.categories = categories
        self.dtype = dtype
        self.handle_unknown = handle_unknown

    def fit(self, X, y=None):
        """Fit the CategoricalEncoder to X.
        Parameters
        ----------
        X : array-like, shape [n_samples, n_feature]
            The data to determine the categories of each feature.
        Returns
        -------
        self
        """

        if self.encoding not in ['onehot', 'onehot-dense', 'ordinal']:
            template = ("encoding should be either 'onehot', 'onehot-dense' "
                        "or 'ordinal', got %s")
            raise ValueError(template % self.handle_unknown)

        if self.handle_unknown not in ['error', 'ignore']:
            template = ("handle_unknown should be either 'error' or "
                        "'ignore', got %s")
            raise ValueError(template % self.handle_unknown)

        if self.encoding == 'ordinal' and self.handle_unknown == 'ignore':
            raise ValueError("handle_unknown='ignore' is not supported for"
                             " encoding='ordinal'")

        X = check_array(X, dtype=np.object, accept_sparse='csc', copy=True)
        n_samples, n_features = X.shape

        self._label_encoders_ = [LabelEncoder() for _ in range(n_features)]

        for i in range(n_features):
            le = self._label_encoders_[i]
            Xi = X[:, i]
            if self.categories == 'auto':
                le.fit(Xi)
            else:
                valid_mask = np.in1d(Xi, self.categories[i])
                if not np.all(valid_mask):
                    if self.handle_unknown == 'error':
                        diff = np.unique(Xi[~valid_mask])
                        msg = ("Found unknown categories {0} in column {1}"
                               " during fit".format(diff, i))
                        raise ValueError(msg)
                le.classes_ = np.array(np.sort(self.categories[i]))

        self.categories_ = [le.classes_ for le in self._label_encoders_]

        return self

    def transform(self, X):
        """Transform X using one-hot encoding.
        Parameters
        ----------
        X : array-like, shape [n_samples, n_features]
            The data to encode.
        Returns
        -------
        X_out : sparse matrix or a 2-d array
            Transformed input.
        """
        X = check_array(X, accept_sparse='csc', dtype=np.object, copy=True)
        n_samples, n_features = X.shape
        X_int = np.zeros_like(X, dtype=np.int)
        X_mask = np.ones_like(X, dtype=np.bool)

        for i in range(n_features):
            valid_mask = np.in1d(X[:, i], self.categories_[i])

            if not np.all(valid_mask):
                if self.handle_unknown == 'error':
                    diff = np.unique(X[~valid_mask, i])
                    msg = ("Found unknown categories {0} in column {1}"
                           " during transform".format(diff, i))
                    raise ValueError(msg)
                else:
                    # Set the problematic rows to an acceptable value and
                    # continue `The rows are marked `X_mask` and will be
                    # removed later.
                    X_mask[:, i] = valid_mask
                    X[:, i][~valid_mask] = self.categories_[i][0]
            X_int[:, i] = self._label_encoders_[i].transform(X[:, i])

        if self.encoding == 'ordinal':
            return X_int.astype(self.dtype, copy=False)

        mask = X_mask.ravel()
        n_values = [cats.shape[0] for cats in self.categories_]
        n_values = np.array([0] + n_values)
        indices = np.cumsum(n_values)

        column_indices = (X_int + indices[:-1]).ravel()[mask]
        row_indices = np.repeat(np.arange(n_samples, dtype=np.int32),
                                n_features)[mask]
        data = np.ones(n_samples * n_features)[mask]

        out = sparse.csc_matrix((data, (row_indices, column_indices)),
                                shape=(n_samples, indices[-1]),
                                dtype=self.dtype).tocsr()
        if self.encoding == 'onehot-dense':
            return out.toarray()
        else:
            return out

In [27]:
#from sklearn.preprocessing import CategoricalEncoder # in future versions of Scikit-Learn

cat_encoder = CategoricalEncoder()
df_cat_reshaped = df_cat.values.reshape(-1, 1)
df_cat_1hot = cat_encoder.fit_transform(df_cat_reshaped)
df_cat_1hot

<18000x7 sparse matrix of type '<class 'numpy.float64'>'
	with 18000 stored elements in Compressed Sparse Row format>

In [28]:
from sklearn.base import BaseEstimator, TransformerMixin

# column index
rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(tarin.values)

NameError: name 'tarin' is not defined

In [29]:
from sklearn.base import BaseEstimator, TransformerMixin

# Create a class to select numerical or categorical columns 
# since Scikit-Learn doesn't handle DataFrames yet
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [30]:
from sklearn.preprocessing import Imputer

imputer = Imputer(strategy="median")

In [31]:
imputer.fit(df_num)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [35]:
num_attribs = list(df_num)
cat_attribs = ['SEX','EDUCATION','MARRIAGE']

num_pipeline = Pipeline([
        ('selector', DataFrameSelector(num_attribs)),
        ('imputer', Imputer(strategy="median")),
        #('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cat_attribs)),
        ('cat_encoder', CategoricalEncoder(encoding="onehot-dense")),
    ])

In [36]:
from sklearn.pipeline import FeatureUnion

full_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])

In [37]:
train_prepared = full_pipeline.fit_transform(train)
train_prepared

array([[ 1.70998663,  0.71002792, -0.01119829, ...,  1.        ,
         0.        ,  0.        ],
       [-0.44574337,  0.05836044, -0.88379222, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.70911198, -0.70191828, -0.01119829, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.90768551, -1.02775201, -1.75638616, ...,  0.        ,
         1.        ,  0.        ],
       [-0.7537048 , -1.13636326, -0.01119829, ...,  0.        ,
         1.        ,  0.        ],
       [-0.06079159,  0.05836044, -1.75638616, ...,  1.        ,
         0.        ,  0.        ]])

KNN classifier

In [38]:
from sklearn.neighbors import KNeighborsClassifier
ar = [3, 5, 10, 20]
for i in ar:
    neigh = KNeighborsClassifier(n_neighbors=i)
neigh.fit(train_prepared,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=20, p=2,
           weights='uniform')

In [39]:
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=20, p=2,
           weights='uniform')

ROC curve for KNN clasifier

In [42]:
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(y_train, neigh)

TypeError: Expected sequence or array-like, got estimator KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=20, p=2,
           weights='uniform')

In [119]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=train_prepared, n_features=4,
                            n_informative=2, n_redundant=0,
                            random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X, y)

TypeError: only length-1 arrays can be converted to Python scalars

#### Conclusions?

Explain your results and choices

Q2. (Optional) Write a function that can shift an MNIST image in any direction (left, right, up, or down) by one pixel. Then, for each image in the training set, create four shifted copies (one per direction) and add them to the training set. Finally, train your best model on this expanded training set and measure its accuracy on the test set. You should observe that your model performs even better now! This technique of artificially growing the training set is called data augmentation or training set expansion.

### Conclusions

### Submit your notebook

Submit your solution here
https://goo.gl/forms/VKD7Zwu54oHjutDc2
Make sure you rename your notebook to    
W3_rachit01.ipynb